id = "bhive/hsw_000172_48d84fc0"
description = "BHive HSW raw basic block sample"
tags = ["bhive", "raw", "hsw"]

[input]
format = "hex"
hex = "4c8dbc24200100004889842490010000c784242801000000000000c784242c01000004000000498d47104889842420010000488b4538f6400104"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/hsw.csv"
measuredCyclesPer100Iterations = 397.0
measuredCyclesPerIteration = 3.97

[run]
arches = ["HSW"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
