id = "bhive/hsw_000979_73600d3b"
description = "BHive HSW raw basic block sample"
tags = ["bhive", "raw", "hsw"]

[input]
format = "hex"
hex = "4801d0488b742420488d90980000004989c448895630"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/hsw.csv"
measuredCyclesPer100Iterations = 197.0
measuredCyclesPerIteration = 1.97

[run]
arches = ["HSW"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
