id = "bhive/hsw_000217_ceba52b3"
description = "BHive HSW raw basic block sample"
tags = ["bhive", "raw", "hsw"]

[input]
format = "hex"
hex = "415741564989f641554989fd41544589c4554889d5534881ecb8020000488b421044894c2420894c24280fb738"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/hsw.csv"
measuredCyclesPer100Iterations = 943.0
measuredCyclesPerIteration = 9.43

[run]
arches = ["HSW"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
