id = "bhive/hsw_000202_4f73e73b"
description = "BHive HSW raw basic block sample"
tags = ["bhive", "raw", "hsw"]

[input]
format = "hex"
hex = "488b9528ffffffc4a17a100402c5fa1145ccc5fc2845b0488b5590482b9570ffffff4883fa07"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/hsw.csv"
measuredCyclesPer100Iterations = 1497.0
measuredCyclesPerIteration = 14.97

[run]
arches = ["HSW"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
