id = "bhive/hsw_000185_57cb7310"
description = "BHive HSW raw basic block sample"
tags = ["bhive", "raw", "hsw"]

[input]
format = "hex"
hex = "0fb7c0486304834801d8"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/hsw.csv"
measuredCyclesPer100Iterations = 697.0
measuredCyclesPerIteration = 6.97

[run]
arches = ["HSW"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
