id = "bhive/hsw_000795_b922a469"
description = "BHive HSW raw basic block sample"
tags = ["bhive", "raw", "hsw"]

[input]
format = "hex"
hex = "48837c24080041bd01000000"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/hsw.csv"
measuredCyclesPer100Iterations = 75.0
measuredCyclesPerIteration = 0.75

[run]
arches = ["HSW"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
