id = "bhive/ivb_000716_6a36b96d"
description = "BHive IVB raw basic block sample"
tags = ["bhive", "raw", "ivb"]

[input]
format = "hex"
hex = "8b8424b8000000488d8c24800200004801e885c0898424b800000048894c2448488b4c2450488d6910"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/ivb.csv"
measuredCyclesPer100Iterations = 598.0
measuredCyclesPerIteration = 5.98

[run]
arches = ["IVB"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
