id = "bhive/ivb_000517_e42a12e6"
description = "BHive IVB raw basic block sample"
tags = ["bhive", "raw", "ivb"]

[input]
format = "hex"
hex = "8990a00500008b9060040000458ba65c01000089d183c9044585e4898860040000"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/ivb.csv"
measuredCyclesPer100Iterations = 605.0
measuredCyclesPerIteration = 6.05

[run]
arches = ["IVB"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
