id = "bhive/ivb_000308_d00970f9"
description = "BHive IVB raw basic block sample"
tags = ["bhive", "raw", "ivb"]

[input]
format = "hex"
hex = "4983ec18498b4424104885c0"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/ivb.csv"
measuredCyclesPer100Iterations = 121.0
measuredCyclesPerIteration = 1.21

[run]
arches = ["IVB"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
