id = "bhive/ivb_000638_55a6d554"
description = "BHive IVB raw basic block sample"
tags = ["bhive", "raw", "ivb"]

[input]
format = "hex"
hex = "488b8424b0010000488d4b384489e2488b7810488b70204c8b07"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/ivb.csv"
measuredCyclesPer100Iterations = 223.0
measuredCyclesPerIteration = 2.23

[run]
arches = ["IVB"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
