id = "bhive/ivb_000339_66c2da75"
description = "BHive IVB raw basic block sample"
tags = ["bhive", "raw", "ivb"]

[input]
format = "hex"
hex = "4a8b14284489e14c89f64c89ff4983c508"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/ivb.csv"
measuredCyclesPer100Iterations = 142.0
measuredCyclesPerIteration = 1.42

[run]
arches = ["IVB"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
