id = "bhive/skl_000011_66b0ef67"
description = "BHive SKL raw basic block sample"
tags = ["bhive", "raw", "skl"]

[input]
format = "hex"
hex = "4883fa0d"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/skl.csv"
measuredCyclesPer100Iterations = 21.0
measuredCyclesPerIteration = 0.21

[run]
arches = ["SKL"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
