id = "bhive/skl_000396_02967fb7"
description = "BHive SKL raw basic block sample"
tags = ["bhive", "raw", "skl"]

[input]
format = "hex"
hex = "415741564189ce41554989d541544989fc554889f55331db4883ec488b5638488d44241f4c8d7c242085d24889442408"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/skl.csv"
measuredCyclesPer100Iterations = 728.0
measuredCyclesPerIteration = 7.28

[run]
arches = ["SKL"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
