id = "bhive/skl_000028_8ce2b8c3"
description = "BHive SKL raw basic block sample"
tags = ["bhive", "raw", "skl"]

[input]
format = "hex"
hex = "448b44240c450fb6ce4489e94489e24889de4889c74889c5"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/skl.csv"
measuredCyclesPer100Iterations = 173.0
measuredCyclesPerIteration = 1.73

[run]
arches = ["SKL"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
