id = "bhive/skl_000641_1951782d"
description = "BHive SKL raw basic block sample"
tags = ["bhive", "raw", "skl"]

[input]
format = "hex"
hex = "554889fd534889f34883ec18c5fb100ec5f928c1c5fb114c2408"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/skl.csv"
measuredCyclesPer100Iterations = 307.0
measuredCyclesPerIteration = 3.07

[run]
arches = ["SKL"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
