id = "bhive/skl_000807_11a61e75"
description = "BHive SKL raw basic block sample"
tags = ["bhive", "raw", "skl"]

[input]
format = "hex"
hex = "498b16488d43184c8973204889531848894208498906488d7424304889df"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/skl.csv"
measuredCyclesPer100Iterations = 396.0
measuredCyclesPerIteration = 3.96

[run]
arches = ["SKL"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
