id = "bhive/skl_000279_fc7e4d49"
description = "BHive SKL raw basic block sample"
tags = ["bhive", "raw", "skl"]

[input]
format = "hex"
hex = "4883c6104889fb488b5424104c8b1e4c8b46084d2bc3493bf8490f43d8483bd8480f43d849c1e3054c031a"
source = "https://raw.githubusercontent.com/ithemal/bhive/master/benchmark/throughput/skl.csv"
measuredCyclesPer100Iterations = 400.0
measuredCyclesPerIteration = 4.0

[run]
arches = ["SKL"]
alignmentOffset = 0
initPolicy = "diff"
noMicroFusion = false
noMacroFusion = false
simpleFrontEnd = false
minIterations = 10
minCycles = 500
